//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funkcionalnost_prijave
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int BrojRezervacije { get; set; }
        public string ImeGosta { get; set; }
        public string EmailGosta { get; set; }
        public string BrojStola { get; set; }
        public string BrojOsoba { get; set; }
        public System.DateTime DatumVrijeme { get; set; }
        public int Restoran { get; set; }
    }
}
