//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotekeVanjske
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int IDJela { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Cijena { get; set; }
        public int Restoran { get; set; }
        public string Vrsta { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
