//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotekeVanjske
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ID { get; set; }
        public int Zaposlenik { get; set; }
        public string ImeZaposlenika { get; set; }
        public int Smjena { get; set; }
        public int Restoran { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
